//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace マイメモ帳.Value.Color {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Custom {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Custom() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("マイメモ帳.Value.ColorName.Custom", typeof(Custom).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   FFE1E1E1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buttonBackColor {
            get {
                return ResourceManager.GetString("buttonBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFFFFFFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string buttonForeColor {
            get {
                return ResourceManager.GetString("buttonForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FF000000 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string formBackColor {
            get {
                return ResourceManager.GetString("formBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFF0F0F0 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string formForeColor {
            get {
                return ResourceManager.GetString("formForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFFFFFFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuStripBackColor {
            get {
                return ResourceManager.GetString("menuStripBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FF000000 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string menuStripForeColor {
            get {
                return ResourceManager.GetString("menuStripForeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FF000000 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string textBackColor {
            get {
                return ResourceManager.GetString("textBackColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FFFFFFFF に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string textForeColor {
            get {
                return ResourceManager.GetString("textForeColor", resourceCulture);
            }
        }
    }
}
